version: 2

workflows:
  version: 2
  release:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - test:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
  build:
    jobs:
        - build
        - test
jobs:
  build:
    docker:
      - image: circleci/golang:1.13     
    steps:
      - checkout

      - run:
          name: Build
          command: make release
          no_output_timeout: 30m
          
      - persist_to_workspace:
          root: .
          paths:
            - artifacts   
  
  test:
    docker:
      - image: circleci/golang:1.13
      - image: fourplusone/docker-atlas:jira-latest

    steps:
      - checkout

      - run:
          name: Wait for JIRA
          command: |
            while :
            do
            curl http://localhost:2990/jira && break;
            sleep 10
            done
      - run:
          name: Testing
          environment: 
            JIRA_URL: http://localhost:2990/jira/
            JIRA_USER: admin
            JIRA_PASSWORD: admin
          command: |
            make test
