version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    steps:
      - checkout

      - run:
          name: Build
          command: make release
  
  test:
    docker:
      - image: circleci/golang:1.12
      - image: fourplusone/docker-atlas:jira-latest

    steps:
      - checkout

      - run:
          name: Wait for JIRA
          command: |
            while :
            do
            curl http://localhost:2990/jira && break;
            sleep 10
            done
      - run:
          name: Testing
          environment: 
            JIRA_URL: http://localhost:2990/jira/
            JIRA_USER: admin
            JIRA_PASSWORD: admin
          command: |
            make test

  publish-github-release:
    requires:
      - build
      - test
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^v\d+\.\d+\.\d+$/
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: ./workspace
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ./workspace/artifacts